[package]
name = "mpchal4"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
rustix = { version = "0.36.6", features = ["default", "fs"] }
